name: baby_coloring_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  permission_handler: ^5.1.0+2
  image_gallery_saver: ^1.6.7
  flutter_colorpicker: ^0.3.5
  screenshot: ^0.2.0
  get:
  toast:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
  fonts:
    - family: PangolinRegular
      fonts:
        - asset: assets/fonts/PangolinRegular.ttf